runner:
  shellcheck:
    cmd: shellcheck --format checkstyle ./**/*.sh
    format: checkstyle
  cspell:
    cmd: cspell lint --no-progress --no-summary --exclude yarn.lock */**
    errorformat:
      - "%f:%l:%c - %m"
