#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

bin_dir=$(dirname "$0")

id=$(date '+%Y-%m-%d')

file="$bin_dir/../pkm/journal/$id.md"

if [[ ! -f "$file" ]]; then
  cat << EOF > "$file"
---
type: Journal
---
# $id Daily

## Tasks

## Meetings

## Misc. Tidbits

EOF
fi

eval "$EDITOR $file"
